name: daicker
version: 0.1.0.0
github: "daicker/daicker"
license: AGPL-3.0
author: "Toru Ikeda"
copyright: "2024 Toru Ikeda"

extra-source-files: []
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/daicker/daicker#readme>

dependencies:
  - base >= 4.7 && < 5
  - megaparsec >= 9.6 && < 10
  - parser-combinators >= 1.0 && < 2
  - scientific >= 0.3 && < 0.4
  - lsp >= 2.6 && < 3
  - text >= 2.0 && < 3
  - optparse-applicative >= 0.18 && < 0.19
  - lens >= 5.0 && < 6
  - aeson >= 2.0 && < 3
  - stm >= 2.0 && < 3
  - co-log-core >= 0.3.0 && < 0.4
  - containers >= 0.6.0 && < 0.7
  - unliftio-core >= 0.2.0 && < 0.3
  - mtl >= 2.0 && < 3
  - exceptions >= 0.10.0 && < 0.11
  - network >= 3.0 && < 4
  - http-client >= 0.7.0 && < 0.8
  - http-types >= 0.12.0 && < 0.13
  - vector >= 0.13.0 && < 0.14
  - bytestring >= 0.11.0 && < 0.12
  - process >= 1.6 && < 1.7
  - hspec >= 2.11 && < 3
  - hspec-core >= 2.11 && < 3
  - hspec-megaparsec >= 2.2 && < 3

library:
  source-dirs: src

executables:
  daicker:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - daicker

tests:
  daicker-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - daicker
